# -*- coding: mbcs -*-
from part import *
from material import *
from section import *
from assembly import *
from step import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
from connectorBehavior import *
mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=200.0)
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(0.0, 0.0), 
    point2=(100.0, 160.0))
mdb.models['Model-1'].sketches['__profile__'].FilletByRadius(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], curve2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[4], nearPoint1=(
    65.6765594482422, 160.033538818359), nearPoint2=(99.8431854248047, 
    156.005706787109), radius=5.0)
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=200.0)
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(0.0, -80.0), 
    point2=(100.0, 80.0))
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=400.0)
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(0.0, 0.0), 
    point2=(100.0, 160.0))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(95.0, 160.0), 
    point2=(100.0, 155.0))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], point1=(
    98.6070709228516, 159.93098449707))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[4], point1=(
    100.095138549805, 158.303207397461))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(95.0, 0.0), point2=(
    100.0, 5.0))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[8], point1=(
    100.151931762695, 2.20946884155273))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[5], point1=(
    97.6537475585938, 0.154670715332031))
mdb.models['Model-1'].Part(dimensionality=TWO_D_PLANAR, name='side-block-left', 
    type=DEFORMABLE_BODY)
mdb.models['Model-1'].parts['side-block-left'].BaseShell(sketch=
    mdb.models['Model-1'].sketches['__profile__'])
del mdb.models['Model-1'].sketches['__profile__']
del mdb.models['Model-1'].parts['side-block-left']
mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=200.0)
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(-50.0, -80.0), 
    point2=(50.0, 80.0))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(45.0, 80.0), point2=
    (50.0, 75.0))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(45.0, -80.0), 
    point2=(50.0, -75.0))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], point1=(
    47.6002655029297, 80.9955139160156))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[4], point1=(
    50.1280670166016, 78.1101531982422))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[5], point1=(
    46.8780364990234, -79.8635559082031))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[7], point1=(
    49.7513885498047, -78.5984191894531))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(45.0, -80.0), 
    point2=(50.0, -75.0))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[9], point1=(
    50.3037796020508, -77.8631744384766))
mdb.models['Model-1'].Part(dimensionality=THREE_D, name='side-block-left', 
    type=DEFORMABLE_BODY)
mdb.models['Model-1'].parts['side-block-left'].BaseSolidExtrude(depth=50.0, 
    sketch=mdb.models['Model-1'].sketches['__profile__'])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].parts.changeKey(fromName='side-block-left', toName=
    'side-block')
# Save by chunyuke0629 on 2025_05_20-02.46.55; build 2024.HF2 2024_03_16-03.54.40 RELr426 191119
from part import *
from material import *
from section import *
from assembly import *
from step import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
from connectorBehavior import *
mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=200.0)
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(-50.0, -100.0), 
    point2=(50.0, 100.0))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(45.0, 100.0), 
    point2=(50.0, 95.0))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(45.0, -100.0), 
    point2=(50.0, -95.0))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-45.0, 100.0), 
    point2=(-50.0, 95.0))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-45.0, -100.0), 
    point2=(-50.0, -95.0))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[2], point1=(
    -50.5659103393555, 97.9512634277344))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], point1=(
    -46.8550720214844, 100.131423950195))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[6], point1=(
    48.3171005249023, 99.9134063720703))
mdb.models['Model-1'].sketches['__profile__'].undo()
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[11], point1=(
    47.1973419189453, 99.9231185913086))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[4], point1=(
    49.9602584838867, 98.4858779907227))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[5], point1=(
    49.3627090454102, -100.017684936523))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[13], point1=(
    50.0494613647461, -98.4588088989258))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[10], point1=(
    -50.0807685852051, -99.4222412109375))
mdb.models['Model-1'].sketches['__profile__'].autoTrimCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[14], point1=(
    -48.4813117980957, -100.021301269531))
mdb.models['Model-1'].Part(dimensionality=THREE_D, name='center-block', type=
    DEFORMABLE_BODY)
mdb.models['Model-1'].parts['center-block'].BaseSolidExtrude(depth=60.0, 
    sketch=mdb.models['Model-1'].sketches['__profile__'])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].parts['center-block'].Round(edgeList=(
    mdb.models['Model-1'].parts['center-block'].edges[4], 
    mdb.models['Model-1'].parts['center-block'].edges[6], 
    mdb.models['Model-1'].parts['center-block'].edges[16], 
    mdb.models['Model-1'].parts['center-block'].edges[18]), radius=5.0)
del mdb.models['Model-1'].parts['center-block']
mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=200.0)
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(-50.0, -100.0), 
    point2=(50.0, 100.0))
mdb.models['Model-1'].Part(dimensionality=THREE_D, name='center-block', type=
    DEFORMABLE_BODY)
mdb.models['Model-1'].parts['center-block'].BaseSolidExtrude(depth=60.0, 
    sketch=mdb.models['Model-1'].sketches['__profile__'])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].parts['center-block'].Chamfer(edgeList=(
    mdb.models['Model-1'].parts['center-block'].edges[0], 
    mdb.models['Model-1'].parts['center-block'].edges[1], 
    mdb.models['Model-1'].parts['center-block'].edges[2], 
    mdb.models['Model-1'].parts['center-block'].edges[3], 
    mdb.models['Model-1'].parts['center-block'].edges[5], 
    mdb.models['Model-1'].parts['center-block'].edges[7], 
    mdb.models['Model-1'].parts['center-block'].edges[8], 
    mdb.models['Model-1'].parts['center-block'].edges[9]), length=5.0)
mdb.models['Model-1'].Material(name='Material-1')
mdb.models['Model-1'].materials['Material-1'].Density(table=((2.65426e-09, ), 
    ))
mdb.models['Model-1'].materials['Material-1'].Elastic(table=((30000.0, 0.25), 
    ))
mdb.models['Model-1'].materials.changeKey(fromName='Material-1', toName=
    'granite')
mdb.models['Model-1'].HomogeneousSolidSection(material='granite', name=
    'granite-homogeneous', thickness=None)
mdb.models['Model-1'].parts['center-block'].Set(cells=
    mdb.models['Model-1'].parts['center-block'].cells.getSequenceFromMask((
    '[#1 ]', ), ), name='center-block')
mdb.models['Model-1'].parts['center-block'].SectionAssignment(offset=0.0, 
    offsetField='', offsetType=MIDDLE_SURFACE, region=
    mdb.models['Model-1'].parts['center-block'].sets['center-block'], 
    sectionName='granite-homogeneous', thicknessAssignment=FROM_SECTION)
mdb.models['Model-1'].parts['side-block'].Set(cells=
    mdb.models['Model-1'].parts['side-block'].cells.getSequenceFromMask((
    '[#1 ]', ), ), name='side-block')
mdb.models['Model-1'].parts['side-block'].SectionAssignment(offset=0.0, 
    offsetField='', offsetType=MIDDLE_SURFACE, region=
    mdb.models['Model-1'].parts['side-block'].sets['side-block'], sectionName=
    'granite-homogeneous', thicknessAssignment=FROM_SECTION)
mdb.models['Model-1'].rootAssembly.DatumCsysByDefault(CARTESIAN)
mdb.models['Model-1'].rootAssembly.Instance(dependent=OFF, name='center-block', 
    part=mdb.models['Model-1'].parts['center-block'])
mdb.models['Model-1'].rootAssembly.Instance(dependent=OFF, name=
    'side-block-left', part=mdb.models['Model-1'].parts['side-block'])
mdb.models['Model-1'].rootAssembly.instances['side-block-left'].translate(
    vector=(110.0, 0.0, 0.0))
mdb.models['Model-1'].rootAssembly.translate(instanceList=('side-block-left', )
    , vector=(-210.0, -20.0, 5.0))
mdb.models['Model-1'].rootAssembly.Instance(dependent=OFF, name=
    'side-block-right', part=mdb.models['Model-1'].parts['side-block'])
mdb.models['Model-1'].rootAssembly.instances['side-block-right'].translate(
    vector=(110.0, 0.0, 0.0))
mdb.models['Model-1'].rootAssembly.rotate(angle=180.0, axisDirection=(0.0, 
    -10.0, 0.0), axisPoint=(160.0, 75.0, 50.0), instanceList=(
    'side-block-right', ))
mdb.models['Model-1'].rootAssembly.translate(instanceList=('side-block-right', 
    ), vector=(-110.0, -20.0, -45.0))
# Save by chunyuke0629 on 2025_05_20-03.04.28; build 2024.HF2 2024_03_16-03.54.40 RELr426 191119
from part import *
from material import *
from section import *
from assembly import *
from step import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
from connectorBehavior import *
mdb.models['Model-1'].rootAssembly.Set(faces=
    mdb.models['Model-1'].rootAssembly.instances['side-block-left'].faces.getSequenceFromMask(
    ('[#20 ]', ), ), name='Set-sideblock-left-bottom')
mdb.models['Model-1'].DisplacementBC(amplitude=UNSET, createStepName='Initial', 
    distributionType=UNIFORM, fieldName='', localCsys=None, name=
    'BC-sideblock-left-bottom', region=
    mdb.models['Model-1'].rootAssembly.sets['Set-sideblock-left-bottom'], u1=
    UNSET, u2=SET, u3=UNSET, ur1=UNSET, ur2=UNSET, ur3=UNSET)
mdb.models['Model-1'].rootAssembly.Set(faces=
    mdb.models['Model-1'].rootAssembly.instances['side-block-right'].faces.getSequenceFromMask(
    ('[#20 ]', ), ), name='Set-sideblock-right-bottom')
mdb.models['Model-1'].DisplacementBC(amplitude=UNSET, createStepName='Initial', 
    distributionType=UNIFORM, fieldName='', localCsys=None, name=
    'BC-sideblock-right-bottom', region=
    mdb.models['Model-1'].rootAssembly.sets['Set-sideblock-right-bottom'], u1=
    UNSET, u2=SET, u3=UNSET, ur1=UNSET, ur2=UNSET, ur3=UNSET)
mdb.models['Model-1'].rootAssembly.Set(faces=
    mdb.models['Model-1'].rootAssembly.instances['side-block-left'].faces.getSequenceFromMask(
    ('[#1 ]', ), ), name='Set-sideblock-left-left')
mdb.models['Model-1'].DisplacementBC(amplitude=UNSET, createStepName='Initial', 
    distributionType=UNIFORM, fieldName='', localCsys=None, name=
    'BC-sideblock-left-left', region=
    mdb.models['Model-1'].rootAssembly.sets['Set-sideblock-left-left'], u1=
    UNSET, u2=UNSET, u3=SET, ur1=UNSET, ur2=UNSET, ur3=UNSET)
mdb.models['Model-1'].rootAssembly.Set(edges=
    mdb.models['Model-1'].rootAssembly.instances['side-block-left'].edges.getSequenceFromMask(
    ('[#1 ]', ), ), name='Set-sideblock-left-frontleft')
mdb.models['Model-1'].DisplacementBC(amplitude=UNSET, createStepName='Initial', 
    distributionType=UNIFORM, fieldName='', localCsys=None, name=
    'BC-sideblock-left-frontleft', region=
    mdb.models['Model-1'].rootAssembly.sets['Set-sideblock-left-frontleft'], 
    u1=SET, u2=UNSET, u3=UNSET, ur1=UNSET, ur2=UNSET, ur3=UNSET)
mdb.models['Model-1'].rootAssembly.Set(edges=
    mdb.models['Model-1'].rootAssembly.instances['side-block-right'].edges.getSequenceFromMask(
    ('[#4 ]', ), ), name='Set-sideblock-right-frontright')
mdb.models['Model-1'].DisplacementBC(amplitude=UNSET, createStepName='Initial', 
    distributionType=UNIFORM, fieldName='', localCsys=None, name=
    'BC-sideblock-right-frontright', region=
    mdb.models['Model-1'].rootAssembly.sets['Set-sideblock-right-frontright'], 
    u1=SET, u2=UNSET, u3=UNSET, ur1=UNSET, ur2=UNSET, ur3=UNSET)
mdb.models['Model-1'].boundaryConditions['BC-sideblock-left-frontleft'].setValues(
    u1=UNSET, u3=SET)
mdb.models['Model-1'].boundaryConditions['BC-sideblock-right-frontright'].setValues(
    u1=UNSET, u3=SET)
mdb.models['Model-1'].boundaryConditions['BC-sideblock-left-left'].setValues(
    u1=SET, u3=UNSET)
mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=200.0)
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(0.0, 0.0), 
    point2=(40.0, 40.0))
mdb.models['Model-1'].Part(dimensionality=THREE_D, name='spring', type=
    DEFORMABLE_BODY)
mdb.models['Model-1'].parts['spring'].BaseSolidExtrude(depth=80.0, sketch=
    mdb.models['Model-1'].sketches['__profile__'])
del mdb.models['Model-1'].sketches['__profile__']
del mdb.models['Model-1'].parts['spring']
mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=200.0)
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(0.0, 0.0), 
    point2=(40.0, 80.0))
mdb.models['Model-1'].Part(dimensionality=THREE_D, name='spring', type=
    DEFORMABLE_BODY)
mdb.models['Model-1'].parts['spring'].BaseSolidExtrude(depth=40.0, sketch=
    mdb.models['Model-1'].sketches['__profile__'])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].parts['center-block'].featurelistInfo()
mdb.models['Model-1'].Material(name='PMMA')
mdb.models['Model-1'].materials['PMMA'].Elastic(table=((3000.0, 0.35), ))
mdb.models['Model-1'].HomogeneousSolidSection(material='PMMA', name='PMMA', 
    thickness=None)
mdb.models['Model-1'].parts['spring'].Set(cells=
    mdb.models['Model-1'].parts['spring'].cells.getSequenceFromMask(('[#1 ]', 
    ), ), name='Set-spring')
mdb.models['Model-1'].parts['spring'].SectionAssignment(offset=0.0, 
    offsetField='', offsetType=MIDDLE_SURFACE, region=
    mdb.models['Model-1'].parts['spring'].sets['Set-spring'], sectionName=
    'PMMA', thicknessAssignment=FROM_SECTION)
# Save by chunyuke0629 on 2025_06_09-14.24.28; build 2024.HF2 2024_03_16-03.54.40 RELr426 191119
from part import *
from material import *
from section import *
from assembly import *
from step import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
from connectorBehavior import *
mdb.models['Model-1'].rootAssembly.Instance(dependent=OFF, name='spring-1', 
    part=mdb.models['Model-1'].parts['spring'])
mdb.models['Model-1'].rootAssembly.features.changeKey(fromName='spring-1', 
    toName='spring')
mdb.models['Model-1'].rootAssembly.features['center-block'].suppress()
mdb.models['Model-1'].rootAssembly.features['center-block'].resume()
mdb.models['Model-1'].rootAssembly.translate(instanceList=('spring', ), vector=
    (-40.0, 100.0, 0.0))
mdb.models['Model-1'].rootAssembly.translate(instanceList=('spring', ), vector=
    (-5.0, 0.0, 10.0))
mdb.models['Model-1'].rootAssembly.translate(instanceList=('spring', ), vector=
    (25.0, 0.0, 0.0))
mdb.models['Model-1'].rootAssembly.featurelistInfo()
mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=200.0)
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(0.0, 0.0), 
    point2=(90.0, 12.7))
mdb.models['Model-1'].Part(dimensionality=THREE_D, name='steel-plate', type=
    DEFORMABLE_BODY)
mdb.models['Model-1'].parts['steel-plate'].BaseSolidExtrude(depth=60.0, sketch=
    mdb.models['Model-1'].sketches['__profile__'])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].Material(name='steel')
mdb.models['Model-1'].materials['steel'].Elastic(table=((200000.0, 0.3), ))
mdb.models['Model-1'].HomogeneousSolidSection(material='steel', name='steel', 
    thickness=None)
mdb.models['Model-1'].parts['steel-plate'].Set(cells=
    mdb.models['Model-1'].parts['steel-plate'].cells.getSequenceFromMask((
    '[#1 ]', ), ), name='Set-steel-plate')
mdb.models['Model-1'].parts['steel-plate'].SectionAssignment(offset=0.0, 
    offsetField='', offsetType=MIDDLE_SURFACE, region=
    mdb.models['Model-1'].parts['steel-plate'].sets['Set-steel-plate'], 
    sectionName='steel', thicknessAssignment=FROM_SECTION)
mdb.models['Model-1'].rootAssembly.Instance(dependent=OFF, name='steel-plate-1'
    , part=mdb.models['Model-1'].parts['steel-plate'])
mdb.models['Model-1'].rootAssembly.translate(instanceList=('steel-plate-1', ), 
    vector=(-45.0, 100.0, 0.0))
mdb.models['Model-1'].StaticStep(name='Normal Load', previous='Initial')
mdb.models['Model-1'].StaticStep(name='Shear Load', previous='Normal Load')
mdb.models['Model-1'].steps['Normal Load'].setValues(nlgeom=ON)
# Save by chunyuke0629 on 2025_06_09-14.41.54; build 2024.HF2 2024_03_16-03.54.40 RELr426 191119
from part import *
from material import *
from section import *
from assembly import *
from step import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
from connectorBehavior import *
mdb.models['Model-1'].rootAssembly.features.changeKey(fromName='steel-plate-1', 
    toName='steel-plate')
mdb.models['Model-1'].rootAssembly.features['steel-plate'].suppress()
mdb.models['Model-1'].rootAssembly.features['steel-plate'].resume()
mdb.models['Model-1'].rootAssembly.translate(instanceList=('spring', ), vector=
    (0.0, 12.7, 0.0))
mdb.models['Model-1'].rootAssembly.Surface(name='Surf-sideblock-right-right', 
    side1Faces=
    mdb.models['Model-1'].rootAssembly.instances['side-block-left'].faces.getSequenceFromMask(
    ('[#1 ]', ), ))
mdb.models['Model-1'].Pressure(amplitude=UNSET, createStepName='Normal Load', 
    distributionType=UNIFORM, field='', magnitude=-10.0, name='normal-load', 
    region=
    mdb.models['Model-1'].rootAssembly.surfaces['Surf-sideblock-right-right'])
mdb.models['Model-1'].loads['normal-load'].setValues(magnitude=10.0)
mdb.models['Model-1'].rootAssembly.Surface(name='Surf-spring-top', side1Faces=
    mdb.models['Model-1'].rootAssembly.instances['spring'].faces.getSequenceFromMask(
    ('[#2 ]', ), ))
mdb.models['Model-1'].Pressure(amplitude=UNSET, createStepName='Shear Load', 
    distributionType=UNIFORM, field='', magnitude=10.0, name='shear-load', 
    region=mdb.models['Model-1'].rootAssembly.surfaces['Surf-spring-top'])
# Save by chunyuke0629 on 2025_06_09-14.45.41; build 2024.HF2 2024_03_16-03.54.40 RELr426 191119
# Save by chunyuke0629 on 2025_06_09-14.45.42; build 2024.HF2 2024_03_16-03.54.40 RELr426 191119
# Save by chunyuke0629 on 2025_06_09-14.48.11; build 2024.HF2 2024_03_16-03.54.40 RELr426 191119
